import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const monstserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nurzhan's website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${monstserrat.className} bg-gray-800`}>{children}</body>
    </html>
  );
}
